#!/bin/zsh
# sets environment variables for the current workspace
# this should be run from the root of the project directory created by mkspace
prepenv () {
echo "\n   prepenv() commands:"
echo " + export workspace=\"\$(<.conf/.workspace)\""
echo " + export projectname=\"\$(<.conf/.projectname)\""
echo " + chkenv\n"
  export workspace="$(<.conf/.workspace)"
  export projectname="$(<.conf/.projectname)"
  export targets="$(<.conf/.targets)"
  chkenv
};
