#!/bin/zsh
# run some nmap scans of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
nullscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "running first null scan"
  if [ -z "$1" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/nullscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/nullscan-.targets-$(date)
    else 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/nullscan-$2-$(date)
    fi
  fi
  echo "running second null scan"
  if [ -z "$1" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/nullscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/nullscan-.targets-$(date)
    else 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/nullscan-$2-$(date)
    fi
  fi
  echo "null scans complete"
};
