#!/bin/zsh
# run some nmap scans of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
scan () {
  echo "running the following scans:"
  echo " - 2x udp scans"
  echo " - 2x null scans"
  echo " - 2x xmas scans"
  echo "results will be stored in $workspace/.scanning/nmap/..."
  udpscan $1 $2
  nullscan $1 $2
  xmasscan $1 $2
  echo "all scans complete"
};
