#!/bin/zsh
# run some nmap scans of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
udpscan () {
  echo "running first udp scan"
  if [ -z "$1" ]; then 
  sudo nmap -sSUV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/udpscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sSUV -Pn -r -O -iL $1/.conf/.targets -oA $workspace/.scanning/nmap/udpscan-.targets-$(date)
    else 
    sudo nmap -sSUV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/udpscan-$2-$(date)
    fi
  fi
  echo "running second udp scan"
  if [ -z "$1" ]; then 
  sudo nmap -sSUV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/udpscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sSUV -Pn -r -O -iL $1/.conf/.targets -oA $workspace/.scanning/nmap/udpscan-.targets-$(date)
    else 
    sudo nmap -sSUV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/udpscan-$2-$(date)
    fi
  fi
  echo "udp scans complete"
};
