#!/bin/zsh
# run some nmap scans of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
xmasscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi
  
  echo "running first xmas scan"
  if [ -z "$1" ]; then 
    sudo nmap -sXV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/xmasscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sXV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/xmasscan-.targets-$(date)
    else 
    sudo nmap -sXV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/xmasscan-$2-$(date)
    fi
  fi
  echo "running second xmas scan"
  if [ -z "$1" ]; then 
    sudo nmap -sXV -Pn -r -O -iL $workspace/.conf/.targets -oA $workspace/.scanning/nmap/xmasscan-.targets-$(date)
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sXV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/xmasscan-.targets-$(date)
    else 
    sudo nmap -sXV -Pn -r -O -iL $1 -oA $workspace/.scanning/nmap/xmasscan-$2-$(date)
    fi
  fi
  echo "xmas scans complete"
};
