#!/bin/zsh
# run a nse scan of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
fullconscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first tcp connect scan of all 65535 ports 'sudo nmap -sTV -p- -Pn -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap -sTV -p- -Pn -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/fullconscan_65k-.targets-1-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sTV -p- -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/fullconscan_65k-$1-1-$(date +%F)"
    else 
    sudo nmap -sTV -p- -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/fullconscan_65k-$2-1-$(date +%F)"
    fi
  fi
  echo "running second tcp connect scan of all 65535 ports 'sudo nmap -sTV -p- -Pn -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap -sTV -p- -Pn -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/fullconscan_65k-.targets-2-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sTV -p- -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/fullconscan_65k-$1-2-$(date +%F)"
    else 
    sudo nmap -sTV -p- -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/fullconscan_65k-$2-2-$(date +%F)"
    fi
  fi
  echo "syn/udp scans complete"
};
