#!/bin/zsh
# run some nmap scans of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
nullscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first null scan 'sudo nmap -sNV -Pn -r -O'"
  if [ -z "$1" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/nullscan-.targets-1-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/nullscan-$1-1-$(date +%F)"
    else 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/nullscan-$2-1-$(date +%F)"
    fi
  fi
  echo "running second null scan 'sudo nmap -sNV -Pn -r -O'"
  if [ -z "$1" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/nullscan-.targets-2-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/nullscan-$1-2-$(date +%F)"
    else 
    sudo nmap -sNV -Pn -r -O -iL $1 -oA "$workspace/.scanning/nmap/nullscan-$2-2-$(date +%F)"
    fi
  fi
  echo "null scans complete"
};
