#!/bin/zsh
# run a nse scan of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
quickscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first syn/udp scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p-  -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/quickscan-.targets-1-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $1 -oA "$workspace/.scanning/nmap/quickscan-$1-1-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $1 -oA "$workspace/.scanning/nmap/quickscan-$2-1-$(date +%F)"
    fi
  fi
  echo "running second syn/udp scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/quickscan-.targets-2-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $1 -oA "$workspace/.scanning/nmap/quickscan-$1-2-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSU -T5 -p- -r -O -iL $1 -oA "$workspace/.scanning/nmap/quickscan-$2-2-$(date +%F)"
    fi
  fi
  echo "syn/udp scans complete"
};
