#!/bin/zsh
# redirect to updated command: segmentedports

segmentedscan () {
  echo "REPLACED BY: 
      segmentedports 
      [versionscan | synports| udpports | conports ] 
      [start_port] 
      [end_port] 
      [number_of_segments]"
};
