#!/bin/zsh
# run a nse scan of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
synports () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first tcp syn scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4  -r -O -p$1'"
  if [ -z "$1" ]; then 
  echo "!!  This command requires a list of ports as the first argument and optionally an output filename as a second argument"
  echo "!!  Example: 80,443,8080 or 1-1024"
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4 -r -O -p$1 -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synports-$1-1-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4 -r -O -p$1 -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synports-$2-1-$(date +%F)"
    fi
  fi
  echo "running second tcp syn scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4  -r -O -p$1'"
  if [ -z "$1" ]; then 
  echo "!!  This command requires a list of ports as the first argument and optionally an output filename as a second argument"
  echo "!!  Example: 80,443,8080 or 1-1024  "
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4  -r -O -p$1 -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synports-$1-2-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sSV -T4  -r -O -p$1 -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synports-$2-2-$(date +%F)"
    fi
  fi
  echo "tcp syn scans complete"
};
