#!/bin/zsh
# run a nse scan of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
synscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first syn scan 'sudo nmap -sS -T4 -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap -sS -T4 -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synscan-.targets-1-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sS -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/synscan-$1-1-$(date +%F)"
    else 
    sudo nmap -sS -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/synscan-$2-1-$(date +%F)"
    fi
  fi
  echo "running second syn scan 'sudo nmap -sS -T4 -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap -sS -T4 -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/synscan-.targets-2-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap -sS -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/synscan-$1-2-$(date +%F)"
    else 
    sudo nmap -sS -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/synscan-$2-2-$(date +%F)"
    fi
  fi
  echo "syn scans complete"
};
