#!/bin/zsh
# run a nse scan of a given target list
# defaults to the target list in the workspace $workspace/.conf/.targets
# writes results to $workspace/.scanning/nmap/...
udpscan () {
  if [ ! -d "$workspace/.scanning/nmap" ]; then
    mkdir $workspace/.scanning/nmap
  fi

  echo "results will be stored in $workspace/.scanning/nmap/..."
  echo "running first udp scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/udpscan-.targets-1-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/udpscan-$1-1-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/udpscan-$2-1-$(date +%F)"
    fi
  fi
  echo "running second udp scan 'sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O'"
  if [ -z "$1" ]; then 
  sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $workspace/.conf/.targets -oA "$workspace/.scanning/nmap/udpscan-.targets-2-$(date +%F)"
  else 
    if [ -z "$2" ]; then 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/udpscan-$1-2-$(date +%F)"
    else 
    sudo nmap --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl -sU -T4 -r -O -iL $1 -oA "$workspace/.scanning/nmap/udpscan-$2-2-$(date +%F)"
    fi
  fi
  echo "udp scans complete"
};
